In [2]:
import numpy as np

### NUMPY 기본 생성

#### ndim = dim 수, size = 데이터 수, shape = 행렬 형태

In [3]:
mat_1 = np.array([[1,0,1,1],[3,0,2,2]])
mat_1.ndim, mat_1.size, mat_1.shape

(2, 8, (2, 4))

#### reshape는 정말정말 많이씁니다!! 

In [4]:
mat_1.reshape(2,2,2)

array([[[1, 0],
        [1, 1]],

       [[3, 0],
        [2, 2]]])

#### reshape(-1, n)의 -1은 저기에 어떤 수가 들어가도 상관 없다!

In [5]:
mat_1.reshape(-1,2)

array([[1, 0],
       [1, 1],
       [3, 0],
       [2, 2]])

#### flatten은 1dim, 즉 벡터 형태로의 변환

In [6]:
mat_1.flatten()

array([1, 0, 1, 1, 3, 0, 2, 2])

#### Indexing/Slicing 도 역시 많이쓰입니다!!

In [7]:
mat_1[:,1:]

array([[0, 1, 1],
       [0, 2, 2]])

In [8]:
mat_1[1,0]

3

#### option : mat[:,::2] 는 step이 2 라는 것을 의미한다.

#### arange는 matrix를 만들어준다 -----optional : list형태로 변환하고 싶을시 .tolist 활용

In [9]:
np.arange(0,4,1).reshape(2,2)

array([[0, 1],
       [2, 3]])

#### np.zeros,np.ones 역시 많이 사용된다!

In [10]:
np.zeros(shape =(10,))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros(shape =(10,)).reshape(2,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones(shape = (10,))

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones(shape = (10,)).reshape(5,2)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

#### 이외에도 np.identity가 있다. 

In [14]:
np.identity(n=4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

#### np.random.uniform, np.random.normal을 통해서 균등, 정규분포 행렬을 생성할 수 있다. 이것 역시 중요!

In [15]:
np.random.uniform(0,1,20)

array([ 0.71517917,  0.58324007,  0.65720345,  0.29792714,  0.72424549,
        0.69627923,  0.52735996,  0.09628717,  0.69113507,  0.57012393,
        0.7722464 ,  0.45617318,  0.91451602,  0.86910087,  0.63789808,
        0.60974681,  0.18764145,  0.11857474,  0.76556034,  0.46702336])

In [16]:
np.random.normal(0,1,30)

array([-0.29293025, -0.9862716 ,  0.68082615,  2.45564146, -0.69503753,
       -0.2001886 , -0.30250814,  0.70430931, -0.6536286 ,  0.7194288 ,
        0.32352747,  0.25413474, -0.0443479 , -0.44593683,  0.7933411 ,
        0.19371406, -1.35006625,  1.16192081,  1.10188311,  0.49868939,
       -0.70569271,  0.90574041,  0.92426615,  0.6875141 ,  0.95610839,
       -0.72503023, -0.36360406,  0.05968211,  0.7088742 , -0.31573849])

#### axis 는 매우 중요하다!!

In [17]:
mat_1

array([[1, 0, 1, 1],
       [3, 0, 2, 2]])

In [18]:
mat_1.sum(axis = 0)

array([4, 0, 3, 3])

In [19]:
mat_1.sum(axis = 1)

array([3, 7])

In [21]:
np.arange(0,36,1).reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [22]:
np.arange(0,36,1).reshape(3,3,4).sum(axis = 2) ##작은 차원2

array([[  6,  22,  38],
       [ 54,  70,  86],
       [102, 118, 134]])

In [24]:
np.arange(0,36,1).reshape(3,3,4).sum(axis = 0) ## 제일 큰차원 0

array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])

In [25]:
np.arange(0,36,1).reshape(3,3,4).sum(axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57],
       [84, 87, 90, 93]])

####  mean(),std(),exp(),sqrt() 등등이 있다.

In [27]:
mat_1.mean(axis =1)

array([ 0.75,  1.75])

#### np.vstack(), np.hstack() -> v = vertical, h= horizental 하지만, concatenate()가 있다.

#### np.loadtxt() 불러오기, np.savetxt() 저장하기, transpose() ...한국말로 뭐였지..?

#### broadcasting은 잘 쓰면 정말 좋다!! 3x4, 1x4 를 합치는 마법

In [28]:
mat_3 = np.arange(0,12,1).reshape(3,4)
mat_4 = np.arange(0,4,1).reshape(1,4)
mat_3, mat_4

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[0, 1, 2, 3]]))

In [29]:
mat_3 + mat_4

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])